name: Go

on:
  workflow_dispatch:
    inputs:
      REPOSITORY_TYPE:
        description: Repository type
        type: choice
        default: GitHub
        options:
          - GitHub
          - URI

      REPOSITORY_ADDRESS:
        description: Repository address
        required: true

      REPOSITORY_REFERENCE:
        description: Reference for repository
        required: true

      EXPORT_TYPE:
        description: Export type for dependency package
        type: choice
        default: all
        options:
          - all
          - deps
          - vendor

      EXPORT_TAG:
        description: Export tag for dependency package
        required: true

      VENDOR_PATH:
        description: The path of Vendor dir in the vendor dependency package. If need to defined ${S} in ebuild, also needs to be defined this field. Default to using export tag

      SRC_PATH:
        description: The path of Go source code in the repository

      WORKING_IN_TMPFS:
        description: Working in tmpfs
        type: boolean
        default: true

permissions:
  contents: write

jobs:
  generator:
    runs-on: ubuntu-latest

    env:
      TAG: ${{ inputs.EXPORT_TAG }}
      EXPORT: /tmp/export

    steps:
      - name: Create dirs
        run: mkdir -pv ${EXPORT}

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          cache: false
          go-version: "stable"

      - name: Using Tmpfs
        if: ${{ inputs.WORKING_IN_TMPFS }}
        run: sudo mount -t tmpfs tmpfs .

      - name: Checkout repository from GitHub
        if: ${{ inputs.REPOSITORY_TYPE == 'GitHub' }}
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.REPOSITORY_ADDRESS }}
          ref: ${{ inputs.REPOSITORY_REFERENCE }}

      - name: Checkout repository from URI
        if: ${{ inputs.REPOSITORY_TYPE == 'URI' }}
        run: |
          git init
          git remote add source ${{ inputs.REPOSITORY_ADDRESS }}
          git fetch source ${{ inputs.REPOSITORY_REFERENCE }} --depth 1
          git checkout FETCH_HEAD

      - name: Generate vendor
        if: ${{ inputs.EXPORT_TYPE == 'all' || inputs.EXPORT_TYPE == 'vendor' }}
        env:
          VENDOR_PATH: ${{ inputs.VENDOR_PATH == null && inputs.EXPORT_TAG || inputs.VENDOR_PATH }}
        working-directory: ${{ inputs.SRC_PATH == null && '.' || inputs.SRC_PATH }}
        run: |
          go mod vendor -modcacherw -o ${VENDOR_PATH}/vendor
          tar -cf ${EXPORT}/${TAG}-vendor.tar ${VENDOR_PATH}/vendor

      - name: Generate deps
        if: ${{ inputs.EXPORT_TYPE == 'all' || inputs.EXPORT_TYPE == 'deps' }}
        working-directory: ${{ inputs.SRC_PATH == null && '.' || inputs.SRC_PATH }}
        run: |
          GOMODCACHE="$(realpath go-mod)" go mod download -x -modcacherw
          tar -cf ${EXPORT}/${TAG}-deps.tar go-mod

      - name: Compress exported files
        run: xz -zv9T0 ${EXPORT}/*.tar

      - name: Generate notes
        run: |
          printf "\u0060\u0060\u0060Manifest\n" >> note.md
          for i in ${EXPORT}/*.tar.*; do
            printf \
              "DIST %s %s BLAKE2B %s SHA512 %s\n" \
              $(basename $i) \
              $(stat -c%s $i) \
              $(b2sum $i | cut -c-128) \
              $(sha512sum $i | cut -c-128) >> note.md
          done
          printf "\u0060\u0060\u0060" >> note.md

      - name: Create release and upload artifaces
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
        run: gh release create ${TAG} -F note.md ${EXPORT}/*.tar.*
